name: kwtsms
description: Official Dart/Flutter client for the kwtSMS SMS gateway API (kwtsms.com).
version: 0.1.2
homepage: https://www.kwtsms.com/integrations.html
repository: https://github.com/boxlinknet/kwtsms-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  kwtsms: kwtsms

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
